# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dapifer_wrappers", use_symbols = TRUE, package_name = "dapifer")

#' @docType package
#' @usage NULL
#' @useDynLib dapifer, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Return 42 to R
#' @param y A list parameter
#' @export
add <- function(y) .Call(wrap__add, y)


# nolint end
